apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: redis
    resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"

  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'sleeeep 60']
  
